language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.1"
  - "RAILS_VERSION=5.1.0.beta1"

matrix:
  exclude:
    - rvm: 2.2.6
      env: "RAILS_VERSION=5.0.1"

addons:
  code_climate:
    repo_token: 9b174f785a3f1ad8986730da28c2756320f0413067e7e06bad278280f47743fd

after_success:
  - bundle exec codeclimate-test-reporter
